

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mvc_Log4Net2NLog2NLog
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class App_LogEntities : DbContext
{
    public App_LogEntities()
        : base("name=App_LogEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<LogEntry> LogEntries { get; set; }

}

}

